- name: Stop the sandbox instances
  ec2:
    instance_ids: '{{ item }}'
    aws_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
    region: "{{ lookup('env','AWS_REGION') }}"
    state: running
    wait: True
  loop: "{{ server_instance_ids}}"
  when: server_instance_ids
