---
- name: Get EC2 Instance information
  ec2_instance_info:
    instance_ids: "{{ item }}"
    aws_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
    region: "{{ lookup('env','AWS_REGION') }}"
  loop: "{{ instance_ids }}"
  register: result

- name: Create result of the ec2 instances
  template:
    src: information-templates.j2
    dest: /tmp/aws-ec2-information.txt